version: '3.8'

services:
  postgres-obrasync:
    image: postgres:15-alpine
    container_name: postgres_obrasync
    environment:
      POSTGRES_DB: obrasync_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: